name: dev
on:
  push:
    paths-ignore:
      - "**/README.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "docs/**"
jobs:
  set_version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: use VERSION file to support dev build on rel-branch
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

  build:
    needs: [set_version]
    uses: gardenlinux/gardenlinux/.github/workflows/build.yml@94b65dd96cd6a277d205829e03690005233524c0
    with:
      version: ${{ needs.set_version.outputs.VERSION }}
