name: nightly
on:
  schedule:
    - cron: "0 6 * * *"
  # triggered manually
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        type: string
        default: now
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
  build:
    needs: [checkout]
    uses: gardenlinux/gardenlinux/.github/workflows/build.yml@94b65dd96cd6a277d205829e03690005233524c0
    with:
      version: ${{ inputs.version || 'now' }}
  upload_oci:
    name: Run glcli to publish to OCI
    needs: [build]
    # use custom upload_oci.yml as we do not sign the images
    # uses: gardenlinux/gardenlinux/.github/workflows/upload_oci.yml@94b65dd96cd6a277d205829e03690005233524c0
    uses: ./.github/workflows/upload_oci.yml
    with:
      version: ${{ needs.build.outputs.version }}
